namespace KnowledgeBaseService.Services;

/// <summary>
/// Service interface for generating structured answers using LLM
/// </summary>
public interface IAnswerService
{
    /// <summary>
    /// Generates a structured answer based on the question and relevant context from knowledge base
    /// </summary>
    /// <param name="question">The user's question</param>
    /// <param name="relevantContexts">Relevant text chunks from the knowledge base</param>
    /// <returns>A structured answer generated by the LLM</returns>
    Task<string> GenerateAnswerAsync(string question, List<string> relevantContexts);
}

