using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace KnowledgeBaseService.Services;

/// <summary>
/// Service that uses Mistral AI API to generate structured answers based on knowledge base context
/// </summary>
public class MistralAnswerService : IAnswerService
{
    private readonly HttpClient _httpClient;
    private readonly string _apiKey;
    private readonly string _apiUrl;

    /// <summary>
    /// Initializes a new instance of the MistralAnswerService
    /// </summary>
    /// <param name="config">Application configuration containing Mistral API settings</param>
    /// <param name="httpClient">HTTP client for making API requests</param>
    /// <exception cref="InvalidOperationException">Thrown when Mistral API key is not configured</exception>
    public MistralAnswerService(IConfiguration config, HttpClient httpClient)
    {
        _httpClient = httpClient;
        _apiUrl = config["AI:LLM:Mistral:Url"] ?? "https://api.mistral.ai";
        _apiKey = config["AI:LLM:Mistral:ApiKey"] ?? throw new InvalidOperationException("Mistral API key is not configured");
        
        _httpClient.BaseAddress = new Uri(_apiUrl);
        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);
        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    }

    /// <summary>
    /// Generates a well-structured answer using Mistral AI based on the question and relevant context from the knowledge base
    /// </summary>
    /// <param name="question">The user's question to be answered</param>
    /// <param name="relevantContexts">List of relevant text chunks from the knowledge base</param>
    /// <returns>A structured, coherent answer generated by Mistral AI</returns>
    /// <exception cref="InvalidOperationException">Thrown when no context is provided or when the API call fails</exception>
    /// <remarks>
    /// The method instructs Mistral to primarily use the provided context but allows supplementation
    /// with general knowledge to ensure complete, helpful answers
    /// </remarks>
    public async Task<string> GenerateAnswerAsync(string question, List<string> relevantContexts)
    {
        if (relevantContexts == null || relevantContexts.Count == 0)
        {
            throw new InvalidOperationException("No relevant context provided from knowledge base");
        }

        // Combine the contexts into a single context block
        var contextBlock = string.Join("\n\n", relevantContexts.Select((ctx, idx) => 
            $"[Context {idx + 1}]\n{ctx}"));

        // Create the prompt for Mistral
        var systemPrompt = @"You are a helpful assistant that answers questions based STRICTLY on the provided context from the knowledge base.

Your task is to:
1. Read and understand the provided context carefully
2. Answer the user's question using ONLY the information from the provided context
3. Do NOT use any information outside of the provided context
4. If the context does not contain enough information to fully answer the question, clearly state what information is missing
5. Provide a clear, well-structured answer that directly addresses the question
6. Format your answer in a readable way with proper paragraphs and bullet points where appropriate
7. If the provided context is completely unrelated to the question, state that the knowledge base does not contain relevant information

IMPORTANT: You must ONLY use information from the provided context. Do not supplement with external knowledge or general information.";

        var userPrompt = $@"Context from knowledge base:
{contextBlock}

Question: {question}

Please provide a detailed, well-structured answer using ONLY the information from the context above. Do not use any external knowledge.";

        var requestBody = new
        {
            model = "mistral-medium-latest",
            messages = new[]
            {
                new { role = "system", content = systemPrompt },
                new { role = "user", content = userPrompt }
            },
            temperature = 0.7,
            max_tokens = 369
        };

        var jsonContent = JsonSerializer.Serialize(requestBody);
        var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

        try
        {
            var response = await _httpClient.PostAsync("/v1/chat/completions", content);
            response.EnsureSuccessStatusCode();

            var responseBody = await response.Content.ReadAsStringAsync();
            var jsonResponse = JsonDocument.Parse(responseBody);

            var answer = jsonResponse.RootElement
                .GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();

            return answer ?? "Unable to generate an answer.";
        }
        catch (HttpRequestException ex)
        {
            Console.WriteLine($"Error calling Mistral API: {ex.Message}");
            throw new InvalidOperationException($"Failed to generate answer using Mistral API: {ex.Message}", ex);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unexpected error in MistralAnswerService: {ex.Message}");
            throw;
        }
    }
}

